[build]
  command = "npm --workspace library run build && npm --workspace examples/vanilla run build && cp -f library/dist/click2call.* examples/vanilla/dist/"
  publish = "examples/vanilla/dist"

[[headers]]
  for = "/click2call.*.js"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"


